### ISSUE TITLE
Deleting AcroTray.exe results in PDF Printer being broken, and reoccuring error messages

### ISSUE THREAD

**Issue by sn3ak** [bmrf/pdq_deploy_packs#1]
I agree AcroTray.exe should not be loaded, however Deleting it from the system causes harm, At least with Acrobat DC, it causes the PDF Printer to error out, endlessly.

This was an unwelcomed surprise after pushing out Adobe AIR, and then getting inundated with phone calls about broken Acrobat / PDF Printers / etc.

**Comment by vocatus** [comment]
Does the same issue occur if you simply rename `AcroTray.exe` to something else?

**Comment by sn3ak** [comment]
Yes, assuming you kill the process as well.
"Windows cannot find 'C:\Program Files (x86)\Adobe\Acrobat 2015\Acrobat\AcroTray.exe'." when attempting to print to pdf.

**Comment by vocatus** [comment]
Interesting. We don't actually delete AcroTray from that location, so I'm not sure how/what is deleting it. 

Is [this](https://github.com/bmrf/pdq_deploy_packs/blob/master/repository/adobe/acrobat_reader_dc/x86/Adobe%20Acrobat%20Reader%20DC.bat) the code you're using?

edit: Just realized you're talking about pushing the Air installer. I'll ponder the best way to fix it and post back.

**Comment by vocatus** [comment]
OK, I added support for the following CLI switch: `--preserve-acrotray`. You pass that flag to the batch file when called (in PDQ or manually) or permanently set the `PRESERVE_ACROTRAY` variable.

You can grab the updated [installer script here](https://github.com/bmrf/pdq_deploy_packs/blob/master/repository/adobe/air/x86/Adobe%20AIR.bat) and this will also go out in the next version of the PDQ packs. Thanks again.
