### ISSUE TITLE
Update BAT source from deployment to master branch

### ISSUE THREAD

**Issue by seannaesmb** [bmrf/pdq_deploy_packs#15]
First of all thank you for supplying these packs for those of us with a yearly budget of $0.   I was noticing that the bat script for example Java jdk 8 64bit doesn't look to be the same as what is extracted from the 2.5gb download.  Any way of updating the master branch for those who just want the jobs and download their own java version?

**Comment by vocatus** [comment]
Hi @seannaesmb , I don't typically usually update the github copies of everything as often, but I'll try to get the latest ones thrown on here.

**Comment by vocatus** [comment]
Done.

**Comment by seannaesmb** [comment]
I appreciate it!
