### ISSUE TITLE
Interested in moving towards PowerShell?

### ISSUE THREAD

**Issue by abulgatz** [bmrf/pdq_deploy_packs#17]
I have been using your packs for a while (thanks for maintaining them!), and I have considered re-writing some of the batch install scripts in PowerShell, which I think would help with maintenance and updates.

Would you be interested in discussing? Would you accept pull-requests?

**Comment by vocatus** [comment]
The long-term plan has been to move to PowerShell for a while, but I haven't honestly had time (or made time, rather) to start drafting it up.

If you did PR's I'd definitely look them over, although I'd want to keep it forked from `.bat` Tron until there's a functional beta.
