### ISSUE TITLE
Notepad++ Feature Request. Add a switch to [not]delete Start Menu folder

### ISSUE THREAD

**Issue by sn3ak** [bmrf/pdq_deploy_packs#2]
In my environment, it's not desirable to  delete the Start Menu folder. I commented out that line, but wonder if you would be willing to [change|accept patch that changes] that to be wrapped in a switch, so that the batch file is easily updated / while keeping PDQ Deploy configured with a /nodelete to prevent the deletion in the future.

**Comment by vocatus** [comment]
Thanks for the suggestion @sn3ak. Are you saying the batch file itself would accept a switch to leave the Start Menu item intact? (which would then be set in the PDQ job file)

**Comment by sn3ak** [comment]
Correct

Brief Example:
M:\npp.installer.bat /nodelete

code might look like:
IF "%1"=="/nodelete" GOTO skipdelete
if exist "%ALLUSERSPROFILE%\Start Menu\Programs\Notepad++" rmdir /s /q "%ALLUSERSPROFILE%\Start Menu\Programs\Notepad++"
:skipdelete
 popd

I'm rather rusty with batch these days, but that should be pretty close to correct

**Comment by vocatus** [comment]
Done, use the `--preserve-shortcuts` switch or permanently set the `PRESERVE_SHORTCUTS` variable to yes. You can grab the updated script [here](https://github.com/bmrf/pdq_deploy_packs/blob/master/repository/notepad/x86/npp.Installer.bat) and the change will go out in the next version of the PDQ packs. Thanks.
